/**
 * The project-mark allowlist.
 *
 * GENERATED by scripts/gen-repo-icons.mjs, together with media/repo-icons.js
 * (the renderers' path data) — do not hand-edit either one. The two come out of
 * one table on purpose: the host rejects any id not in this list, so a picker
 * that offered one the host had never heard of would be a control that silently
 * does nothing.
 *
 * Order is the catalogue order the picker draws; nothing depends on it.
 */
export const REPO_ICON_IDS = [
  "hexagon", "pentagon", "square", "circle",
  "diamond", "grid_view", "bolt", "spa",
  "eco", "star", "favorite", "shield",
  "encrypted", "key", "extension", "folder_open",
  "rocket_launch", "rocket", "code", "terminal",
  "database", "cloud", "science", "construction",
  "build", "drone", "smart_toy", "robot_2",
  "hub", "quiz", "lightbulb", "contactless",
  "work", "domain", "paid", "analytics",
  "pie_chart", "finance", "graph_2", "trending_up",
  "receipt_long", "storefront", "savings", "handshake",
  "inventory_2", "monitoring", "workspace_premium", "planner_review",
  "mail", "chat_bubble", "sms", "forum",
  "ring_volume", "call", "contact_mail", "alternate_email",
  "campaign", "rss_feed", "voicemail", "podcasts",
  "groups", "diversity_3", "waving_hand", "thumb_up",
  "person", "person_2", "person_3", "person_4",
  "group", "emoji_people", "public", "school",
  "psychology", "pets", "medication", "celebration",
  "travel", "trip", "flight", "luggage",
  "map", "explore", "sailing", "hiking",
  "beach_access", "directions_car", "train", "local_cafe",
  "restaurant", "stadia_controller", "sports_esports", "music_note",
  "palette", "brush", "photo_camera", "menu_book",
] as const;
